from __future__ import annotations
import asyncio
from collections.abc import Callable
from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Any, Optional

from copilot import CopilotClient
from copilot.session import PermissionHandler

from ..sessions.session_manager import SessionManager, TranscriptMessage
from ..queue.command_queue import enqueue_in_lane

TURN_TIMEOUT = 120  # seconds


@dataclass
class AgentTurnEvent:
    type: str  # "delta" | "message" | "tool_start" | "tool_complete" | "idle" | "error"
    content: Optional[str] = None
    tool_name: Optional[str] = None
    error: Optional[str] = None


AgentTurnCallback = Callable[[AgentTurnEvent], None]


class AgentRuntime:
    def __init__(self, session_manager: SessionManager, model: str = "gpt-4o-mini") -> None:
        self._session_manager = session_manager
        self._model = model
        self._client: Optional[CopilotClient] = None
        # One CopilotSession per session key — persists context across turns
        self._copilot_sessions: dict[str, Any] = {}

    async def start(self) -> None:
        self._client = CopilotClient(auto_start=True)
        await self._client.start()
        print("[agent] Copilot client started")

    async def stop(self) -> None:
        for key, session in self._copilot_sessions.items():
            try:
                await session.disconnect()
            except Exception:
                pass
        self._copilot_sessions.clear()
        if self._client:
            await self._client.stop()
            self._client = None
        print("[agent] Copilot client stopped")

    async def run_turn(
        self,
        session_key: str,
        user_message: str,
        on_event: AgentTurnCallback,
    ) -> None:
        lane = f"session:{session_key}"
        print(f"[agent] Queueing runTurn for lane {lane}")

        async def _run() -> str:
            print(f"[agent] Starting runTurn for lane {lane}")
            if not self._client:
                raise RuntimeError("Agent runtime not started")

            # Persist user message to transcript
            entry = await self._session_manager.resolve_or_create(session_key)
            await self._session_manager.append_message(
                session_key,
                TranscriptMessage(
                    role="user",
                    content=user_message,
                    ts=datetime.now(timezone.utc).isoformat(),
                    session_id=entry.session_id,
                ),
            )

            # Get or create CopilotSession (persists context across turns)
            copilot_session = self._copilot_sessions.get(session_key)
            if copilot_session is None:
                copilot_session = await self._client.create_session(
                    model=self._model,
                    on_permission_request=PermissionHandler.approve_all,
                    streaming=True,
                )
                self._copilot_sessions[session_key] = copilot_session

            full_response = ""
            done = asyncio.Event()

            def handle_event(event: Any) -> None:
                nonlocal full_response
                match event.type.value:
                    case "assistant.message_delta":
                        delta = event.data.delta_content or ""
                        if delta:
                            full_response += delta
                            on_event(AgentTurnEvent(type="delta", content=delta))

                    case "assistant.message":
                        content = event.data.content or ""
                        if content and not full_response:
                            full_response = content
                        on_event(AgentTurnEvent(type="message", content=full_response))

                    case "tool.execution_start":
                        tool_name = getattr(event.data, "name", "unknown")
                        on_event(AgentTurnEvent(type="tool_start", tool_name=tool_name))

                    case "tool.execution_complete":
                        tool_name = getattr(event.data, "name", "unknown")
                        on_event(AgentTurnEvent(type="tool_complete", tool_name=tool_name))

                    case "session.idle":
                        on_event(AgentTurnEvent(type="idle"))
                        done.set()

                    case "session.error":
                        error_msg = str(getattr(event, "message", "400"))
                        print(f"[agent] Copilot session error: {error_msg}")

                        mock_content = (
                            f"**Backend Error**\n\n"
                            f"The GitHub Copilot API returned an error: `{error_msg}`.\n\n"
                            f"*This is a mocked response generated by the gateway so you can "
                            f"continue testing the WebSocket pipeline without API access!*"
                        )
                        if not full_response:
                            full_response = mock_content
                        on_event(AgentTurnEvent(type="message", content=mock_content))
                        on_event(AgentTurnEvent(type="idle"))
                        done.set()

            copilot_session.on(handle_event)

            print("[agent] Sending prompt to copilotSession...")
            await copilot_session.send(user_message)
            print("[agent] Prompt sent, waiting for done...")
            await asyncio.wait_for(done.wait(), timeout=TURN_TIMEOUT)

            # Persist assistant response to transcript
            if full_response:
                await self._session_manager.append_message(
                    session_key,
                    TranscriptMessage(
                        role="assistant",
                        content=full_response,
                        ts=datetime.now(timezone.utc).isoformat(),
                        session_id=entry.session_id,
                    ),
                )

            return full_response

        await enqueue_in_lane(lane, _run)
